name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [

  { pattern = "jb.serveraby.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.jb.serveraby.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.jb.serveraby.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.jb.serveraby.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.jb.serveraby.web.id", custom_domain = true },
  { pattern = "support.zoom.us.jb.serveraby.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.jb.serveraby.web.id", custom_domain = true },

  { pattern = "jk.serveraby.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.jk.serveraby.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.jk.serveraby.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.jk.serveraby.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.jk.serveraby.web.id", custom_domain = true },
  { pattern = "support.zoom.us.jk.serveraby.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.jk.serveraby.web.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "2052d9e1b5494957aa98602ad27ed692"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "fbe27826-d657-4426-b9ab-70f160833a74"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/HTML/refs/heads/main/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/HTML/refs/heads/main/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/HTML/refs/heads/main/link.html"
